Repository mmujtabah/CodingChallenges, pull requests merged in 2024-10, with the labels that each got.

#5 Request for adding new Challenges into the Project.
  challenges/CoolKonsole/README.md
  challenges/CoolKonsole/exampleOutput.mp4
  challenges/IndexingMaster/README.md
  challenges/PalindromeString/README.md
  solutions/CoolKonsole/CoolKonsole.py
  solutions/IndexingMaster/IndexingMaster.js
  solutions/IndexingMaster/IndexingMaster.py
  solutions/IndexingMaster/s.json
  solutions/PalindromeString/PalindromeString.js
  solutions/PalindromeString/PalindromeString.py
Labels: hacktoberfest-accepted

#6 Add Solution for Rock_Paper_Scissor_Game
  challenges/Rock_Paper_Scissor_Game/Rock_Paper_Scissor_Game.md
  challenges/Rock_Paper_Scissor_Game/test_example.png
  solutions/Rock_Paper_Scissor_Game/main.py
  solutions/Rock_Paper_Scissor_Game/static/paper.png
  solutions/Rock_Paper_Scissor_Game/static/rock.png
  solutions/Rock_Paper_Scissor_Game/static/scissors.png
  solutions/Rock_Paper_Scissor_Game/templates/index.html
Labels: hacktoberfest-accepted

#8 Added some new challenges. And added javascript solution to CoolKonsole Challenge.
  challenges/SimpleMatrixGen/README.md
  challenges/TableOf/README.md
  solutions/CoolKonsole/CoolKonsole.js
  solutions/IndexingMaster/s.json
  solutions/SimpleMatrixGen/SimpleMatrixGen.py
  solutions/TableOf/TableOf.js
  solutions/TableOf/TableOf.py
Labels: hacktoberfest-accepted

#9 Added 2 more challenges and added SImpleMatrixGen.js for challenge.
  challenges/GetTheSpeedToReach/README.md
  challenges/SimpleAlarm/README.md
  solutions/GetTheSpeedToReach/GetTheSpeedToReach.js
  solutions/GetTheSpeedToReach/GetTheSpeedToReach.py
  solutions/SimpleAlarm/SimpleAlarm.js
  solutions/SimpleAlarm/SimpleAlarm.py
  solutions/SimpleMatrixGen/SimpleMatrixGen.js
Labels: enhancement, hacktoberfest-accepted

#10 Add prime number checker
  challenges/PrimeNumberChecker/readme.MD
  solutions/PrimeNumberChecker/primenumberchecker.py
Labels: hacktoberfest, hacktoberfest-accepted

#11 Rock game
  solutions/Rock_Paper_Scissor_Game/main.py
Labels: hacktoberfest, hacktoberfest-accepted

#13 Add temperature converter program
  challenges/TemperatureConverter/Readme.MD
  solutions/TemperatureConverter/TemperatureConverter.py
Labels: hacktoberfest, hacktoberfest-accepted

#14 Add fibonacci series
  challenges/FibonacciSeries/readme.MD
  solutions/FibonacciSeries/fibonacciSeries.py
Labels: hacktoberfest, hacktoberfest-accepted

#15 JS files update for two solutions
  solutions/PrimeNumberChecker/primenumberchecker.js
  solutions/TemperatureConverter/TemperatureConverter.js
Labels: enhancement, hacktoberfest, hacktoberfest-accepted

#17 JS solution for fizzbuzz
  solutions/fizzbuzz/fizzbuzz.js
Labels: hacktoberfest, hacktoberfest-accepted

#18 Fibonacci in C Language
  solutions/FibonacciSeries/fibonacciSeries.c
Labels: hacktoberfest, hacktoberfest-accepted

#19 Added the fraud detection SOM model
  Advanced/SOM for fraud detection/Credit_Card_Applications.csv
  Advanced/SOM for fraud detection/README.md
  Advanced/SOM for fraud detection/SOMs and prediction of frauds.ipynb
Labels: enhancement, hacktoberfest, hacktoberfest-accepted

#20 Create PrimeNumberChecker.py
  Beginner/solutions/PrimeNumberChecker/PrimeNumberChecker.py
Labels: hacktoberfest, hacktoberfest-accepted

#21 Create Rock-Paper-ScissorGame.py
  Beginner/solutions/Rock_Paper_Scissor_Game/Rock-Paper-ScissorGame.py
Labels: hacktoberfest, hacktoberfest-accepted

#23 Prime Number Checker in Python
  Beginner/solutions/PrimeNumberChecker/primenochecker.py
Labels: hacktoberfest, hacktoberfest-accepted

#24 Added some c++ solutions
  Beginner/solutions/FibonacciSeries/FibonacciSeries.cpp
  Beginner/solutions/PalindromeString/Palindrome.cpp
Labels: hacktoberfest, hacktoberfest-accepted

#25 Added Project ContactsInConsole
  Beginner/challenges/Project_ContactsInConsole/README.md
  Beginner/solutions/Project_ContactsInConsole/Contacts/alihassancods.consolecontact
  Beginner/solutions/Project_ContactsInConsole/Contacts/alizaincodes.consolecontact
  Beginner/solutions/Project_ContactsInConsole/Contacts/mmujtabah.consolecontact
  Beginner/solutions/Project_ContactsInConsole/main.py
Labels: hacktoberfest, hacktoberfest-accepted

#26 Added JSON Solution for Project ContactsInConsole
  Beginner/challenges/Project_ContactsInConsole/README.md
  Beginner/solutions/Project_ContactsInConsole/Using Files Solution/Contacts/alihassancods.consolecontact
  Beginner/solutions/Project_ContactsInConsole/Using Files Solution/Contacts/alizaincodes.consolecontact
  Beginner/solutions/Project_ContactsInConsole/Using Files Solution/Contacts/mmujtabah.consolecontact
  Beginner/solutions/Project_ContactsInConsole/Using Files Solution/main.py
  Beginner/solutions/Project_ContactsInConsole/Using Json Solution/contacts.json
  Beginner/solutions/Project_ContactsInConsole/Using Json Solution/main.py
Labels: enhancement

#27 Added 2 more challenge AverageCalculator and PunctuationRemover.
  Beginner/challenges/CalculateAverage/README.md
  Beginner/challenges/PunctuationRemover/README.md
  Beginner/solutions/CalculateAverage/main.py
  Beginner/solutions/PunctuationRemover/main.py
Labels: hacktoberfest, hacktoberfest-accepted

#28 Contactsinconsole.py
  Beginner/challenges/Project_ContactsInConsole/Contactsinconsole.py
Labels: enhancement, hacktoberfest, hacktoberfest-accepted

#29 Averagecalculater.py
  Beginner/challenges/CalculateAverage/Averagecalculater.py
Labels: enhancement, hacktoberfest, hacktoberfest-accepted

#30 Punctuationremover.py
  Beginner/challenges/PunctuationRemover/Punctuationremover.py
Labels: documentation, hacktoberfest, hacktoberfest-accepted
